---
# https://communities.ca.com/docs/DOC-231149229
- name: 'verify presence of file'
  connection: local
  sudo: no
  local_action: stat path={{cur_dir}}/{{ cara_file }}
  register: cara_cached

- name: "check ROC"
  connection: local
  sudo: no
  local_action: uri url={{ cara_baseurl }} status_code=200
  when: not cara_cached.stat.exists

- name: "download nolio from VM on localhost"
  local_action: get_url url={{ cara_baseurl }}/apps/{{ cara_file }} dest={{cur_dir}}/{{ cara_file }}
  sudo: no
  register: nolio
  when: not cara_cached.stat.exists

- name: 'yum install packages for Nolio'
  action: yum name={{ item }} state=installed
  with_items:
    - compat-glibc-headers
    - compat-glibc
    - libstdc++*.i686
    - kernel-headers

- name: 'verify presence of NolioAgent'
  stat: path=/opt/Nolio/NolioAgent
  register: nolioagent

- name: 'copy nolio agent software to remote'
  copy: src={{cur_dir}}/{{ cara_file }} dest=/home/vagrant/{{ cara_file }} mode=u=rwx,g=rx,o=rx
  when: not nolioagent.stat.exists

- name: 'copy nolio agent software to remote'
  template: src=agent.response.varfile.j2 dest=/home/vagrant/agent.response.varfile owner=vagrant

- name: 'install nolio agent'
  shell: /home/vagrant/{{ cara_file }}  -q -dir {{ nolioagent_dir }} -varfile agent.response.varfile \
  when: not nolioagent.stat.exists

